spring:
    application:
        name: backend

    config:
        import: optional:configserver:http://localhost:8888

    cloud:
        config:
            name: travelingdog
            profile: local

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                "[format_sql]": true

jwt:
    secretKey: asdjrkljakljvkvlwjo9iausoidapjklbkahsiodhrijasdrkljklasjdlkrja # 256비트 이상 권장
    accessTokenValidityInSeconds: 86400 # 24시간

openai:
    api:
        key: sk-dummy-api-key-for-testing-purposes-only
        url: https://api.openai.com/v1/chat/completions
        model: gpt-3.5-turbo

springdoc:
    swagger-ui:
        path: /swagger-ui.html
        api-docs: /api-docs
        default-consumes-media-type: application/json
        default-produces-media-type: application/json
        operationsSorter: method
        tagsSorter: alpha
        tryItOutEnabled: true
        filter: true
