spring:
    application:
        name: backend

    config:
        import: optional:configserver:http://localhost:8888

    cloud:
        config:
            name: travelingdog
            profile: local

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                "[format_sql]": true

jwt:
    secretKey: asdjrkljakljvkvlwjo9iausoidapjklbkahsiodhrijasdrkljklasjdlkrja # 256비트 이상 권장
    accessTokenValidityInSeconds: 86400 # 24시간
    refreshTokenValidityInSeconds: 604800 # 7일

openai:
    api:
        key: sk-dummy-api-key-for-testing-purposes-only
        url: https://api.openai.com/v1/chat/completions
        model: gpt-3.5-turbo

springdoc:
    swagger-ui:
        path: /swagger-ui.html
    api-docs:
        path: /v3/api-docs
    packages-to-scan: com.travelingdog.backend.controller
