spring:
    application:
        name: backend

    config:
        import: optional:configserver:http://20.249.216.130:8888

    cloud:
        config:
            name: travelingdog
            profile: dev
            username: traveling_naru
            password: traveling_narudog_config_server
