apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traveling-backend-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: traveling-api.narudog.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: traveling-backend-service
                port:
                  number: 80 