name: Deploy to Oracle Instance

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            # Config 파일 저장소 복사
            - name: Clone Config Repository
              run: |
                  git clone https://${{ secrets.CONFIG_REPO_PAT }}@${{ secrets.CONFIG_REPO_URL }} config-repo
                  cp -r config-repo/travelingdog-dev.yml ./src/main/resources/application-build.yml

            - name: Setup SSH agent
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build Docker image
              run: |
                  docker build --no-cache -f Dockerfile.development -t ${{ secrets.DOCKER_USERNAME }}/travelingdog-backend:latest .

            - name: Push Docker image to Docker Hub
              run: |
                  docker push ${{ secrets.DOCKER_USERNAME }}/travelingdog-backend:latest

            - name: Install sshpass
              run: sudo apt-get install sshpass

            - name: Deploy to Azure VM
              run: |
                  sshpass -p "${{ secrets.AZURE_SSH_PASS }}" ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_SSH_USER }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
                  export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
                  export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
                  docker pull ${{ secrets.DOCKER_USERNAME }}/travelingdog-backend:latest
                  docker-compose down
                  docker-compose up -d
                  EOF
